// Datos de las estaciones — fácil de editar después
export const ESTACIONES = {
  sushi: {
    nombre: 'Sushi',
    emoji: '🍣',
    secciones: {
      'Sushi': [
        { item: 'Salmón', min: '1 salmón' },
        { item: 'Surimi', min: '5 paquetes' },
        { item: 'Anguila', min: '1 anguila' },
        { item: 'Nori', min: '2 paquetes' },
        { item: 'Philadelphia', min: '1 paquete' },
        { item: 'Masago', min: '1 kg' },
        { item: 'Wasabi', min: '1/2 kg' },
        { item: 'Gari', min: '1/2 kg' },
        { item: 'Soya', min: '1 soya' },
        { item: 'Azúcar', min: '5 kg' },
        { item: 'Ajonjolí Negro', min: '1 kg' },
        { item: 'Ajonjolí Blanco', min: '1 kg' },
        { item: 'Mayonesa', min: '1/2 contenedor' },
        { item: 'Calamar', min: '1 paquete' },
        { item: 'Vinagre', min: '1 botella' },
        { item: 'Atún', min: '2 medallones' },
        { item: 'Hoja de Arroz', min: '1 paquete' },
      ],
    },
  },

  caliente: {
    nombre: 'Caliente',
    emoji: '🔥',
    secciones: {
      'Caliente': [
        { item: 'Arroz', min: '2 bultos' },
        { item: 'Soya', min: '1' },
        { item: 'Udon', min: '1' },
        { item: 'Harusame', min: '1 bolsa' },
        { item: 'Pasta Miso', min: '1' },
        { item: 'Dashi', min: '1 bolsa' },
        { item: 'Ajinomoto', min: '1 bolsa' },
        { item: 'Tofu', min: '1' },
        { item: 'Osha Té Verde', min: '1' },
        { item: 'Wakame', min: '1' },
        { item: 'Azúcar', min: '5 kg' },
        { item: 'Maizena', min: '1 kg' },
        { item: 'Soya Kikkoman', min: '1/2' },
        { item: 'Aceite de Ajonjolí', min: '1' },
        { item: 'Sal', min: '1' },
        { item: 'Vino Blanco', min: '1' },
        { item: 'Pimienta Blanca', min: '1' },
        { item: 'Furikake', min: '1' },
        { item: 'Microdyn', min: '1' },
        { item: 'Pescado', min: '1 bolsa' },
        { item: 'Crema Personal', min: '1' },
      ],
      'Empanizados': [
        { item: 'Aceite', min: '3 aceites' },
        { item: 'Panko', min: '1/4 bulto' },
        { item: 'Queso Manchego', min: '1/4 paquete' },
        { item: 'Cajeta', min: '1' },
        { item: 'Chocolate', min: '1' },
        { item: 'Mermelada', min: '1' },
        { item: 'Oreos', min: '1/2 caja' },
        { item: 'Helado de Vainilla', min: '1/4 helado' },
        { item: 'Pan para Helado', min: '1 pan' },
        { item: 'Tempuraco', min: '1 bolsa' },
        { item: 'Huevo', min: '1 cono' },
      ],
      'Loza': [
        { item: 'Jabón Roma', min: '1/4 bolsa' },
        { item: 'Cloro', min: '1/4 contenedor' },
        { item: 'Fibra Verde', min: '1 fibra' },
        { item: 'Fibra de Metal', min: '1 fibra' },
        { item: 'Bolsa Basura', min: '1 bolsa' },
      ],
    },
  },

  verduras: {
    nombre: 'Verduras y Carnes',
    emoji: '🥬',
    secciones: {
      'Verduras': [
        { item: 'Calabaza', min: '5 kg' },
        { item: 'Zanahoria', min: '5 kg' },
        { item: 'Cebolla', min: '2 kg' },
        { item: 'Cebollín', min: '1 paquete' },
        { item: 'Morrón', min: '2 kg' },
        { item: 'Champiñón', min: '2 kg' },
        { item: 'Jengibre', min: '1 kg' },
        { item: 'Chile', min: '2 kg' },
        { item: 'Limón', min: '2 kg' },
        { item: 'Plátano Macho', min: '3 kg' },
        { item: 'Pepino', min: '5 kg' },
        { item: 'Germen de Soya', min: '2 kg' },
        { item: 'Aguacate', min: '5 kg' },
        { item: 'Jitomate', min: '2 kg' },
        { item: 'Brócoli', min: '5 kg' },
        { item: 'Coliflor', min: '5 kg' },
        { item: 'Lechuga', min: '1 lechuga' },
        { item: 'Fresa', min: '1 domo' },
        { item: 'Piña', min: '1/2 piña' },
        { item: 'Manzana', min: '4 kg' },
        { item: 'Jalapeño', min: '1 kg' },
        { item: 'Habanero', min: '1 kg' },
        { item: 'Otro', min: '' },
      ],
      'Carnes y Pescados': [
        { item: 'Pollo', min: '5 kg' },
        { item: 'Pechuga de Pollo', min: '2 kg' },
        { item: 'Res', min: '2 kg' },
        { item: 'Pulpo', min: '2 kg' },
        { item: 'Pescado', min: '1 bolsa' },
        { item: 'Calamar', min: '1 paquete' },
        { item: 'Huevo', min: '2 conos' },
      ],
    },
  },
masao: {
    nombre: 'Masao',
    emoji: '🦐',
    secciones: {
      'Masao': [
        { item: 'Camarón', min: '5 kg' },
        { item: 'Pulpo', min: '2 kg' },
        { item: 'Ramen', min: '1 caja' },
        { item: 'Salmón', min: '1 lonja' },
        { item: 'Ajonjolí Blanco', min: '1 kg' },
        { item: 'Ajonjolí Negro', min: '1 kg' },
        { item: 'Calamar', min: '1 paquete' },
        { item: 'Ajo Italiano', min: '1/2 kg' },
        { item: 'Mango', min: '5 kg' },
        { item: 'Kushis', min: '1 paquete' },
        { item: 'Té con Miel', min: '1/2 caja' },
        { item: 'Aceite de Oliva', min: '1/2 contenedor' },
        { item: 'Togarashi', min: '1 paquete' },
        { item: 'Arrachera', min: '1/2 kg' },
        { item: 'Jugo de Lychee', min: '1/2 caja' },
        { item: 'Catsup', min: '1' },
        { item: 'Sapporo', min: '1 caja' },
        { item: 'Ajinomoto', min: '1 kg' },
        { item: 'Jugo de Uva', min: '1/2 caja' },
      ],
    },
  },
  unicel: {
    nombre: 'Unicel',
    emoji: '📦',
    secciones: {
      'Unicel': [
        { item: 'Hamburguesero', min: '2 paquetes' },
        { item: 'Tazón para Sopa', min: '4 bolsas' },
        { item: 'Tapas para Tazón', min: '4 bolsas' },
        { item: '7x7', min: '1 paquete' },
        { item: '8x8', min: '1 paquete' },
        { item: 'Vasitos Soya llevar', min: '3 paquetes' },
        { item: 'Tapas Soya llevar', min: '3 paquetes' },
        { item: 'Vasitos de anguila', min: '2 paquetes' },
        { item: 'Tapas de anguila', min: '2 paquetes' },
        { item: 'Playo', min: '1' },
        { item: 'Aluminio', min: '1' },
      ],
      'Caluri': [
        { item: 'Hamburguesero', min: '2 paquetes' },
        { item: 'Tazón para Sopa', min: '4 bolsas' },
        { item: 'Tapas para Tazón', min: '4 bolsas' },
        { item: '7x7', min: '1 paquete' },
        { item: '8x8', min: '1 paquete' },
        { item: 'Vasitos Soya llevar', min: '3 paquetes' },
        { item: 'Tapas Soya llevar', min: '3 paquetes' },
        { item: 'Vasitos de anguila', min: '2 paquetes' },
        { item: 'Tapas de anguila', min: '2 paquetes' },
        { item: 'Playo', min: '1' },
        { item: 'Aluminio', min: '1' },
        { item: 'Coca de Lata', min: '1 paquete' },
        { item: 'Coca Sin Azúcar de Lata', min: '1 paquete' },
        { item: 'Mundet de Lata', min: '1 paquete' },
        { item: 'Delaware de Lata', min: '1 paquete' },
        { item: 'Agua Mineral de Lata', min: '1 paquete' },
        { item: 'Sprite de Lata', min: '1 paquete' },
      ],
    },
  },

  mesas: {
    nombre: 'Mesas',
    emoji: '🍽️',
    secciones: {
      'Mesas': [
        { item: 'Palillos', min: '2 paquetes' },
        { item: 'Agua Mineral', min: '2 litros' },
        { item: 'Boing', min: '1 paquete' },
        { item: 'Servilleta Fina', min: '2 paquetes chicos' },
        { item: 'Servilleta Lunch', min: '1 paquete' },
        { item: 'Catsup', min: '1/2 bote' },
        { item: 'Mentas', min: '1 paquete' },
        { item: 'Jarabe Dulce', min: '2 litros' },
        { item: 'Vino Tinto', min: '1 litro' },
        { item: 'Calpis', min: '1 litro' },
        { item: 'Cerveza Clara', min: '1/2 caja' },
        { item: 'Cerveza Oscura', min: '1/2 caja' },
        { item: 'Agua embotellada', min: '1/2 bolsa' },
        { item: 'Sanitas', min: '4 paquetes' },
        { item: 'Papel de Baño', min: '3 rollos' },
        { item: 'Jabón para lavamanos', min: '2 litros' },
        { item: 'Pinol', min: '1/4' },
        { item: 'Soyeras chicas', min: '2 paquetes' },
        { item: 'Bolsa Grande', min: '1/4' },
        { item: 'Bolsa Mediana', min: '1/4' },
        { item: 'Bolsa Chica', min: '1/4' },
        { item: 'Playo', min: '2 playos' },
        { item: 'Cerezas', min: '1/4 contenedor' },
        { item: 'Jugo Lychee', min: '1/2 caja' },
        { item: 'Jugo de Uva', min: '1/2 caja' },
        { item: 'Té Verde con Miel', min: '1/2 caja' },
        { item: 'Vasitos Soya Llevar', min: '2 bolsas' },
        { item: 'Tapas Soya Llevar', min: '2 bolsas' },
        { item: 'Windex', min: '1' },
        { item: 'Trapeador', min: '1 trapeador' },
        { item: 'Grapas', min: '1 cajita' },
        { item: 'Plumas', min: '1 cajita' },
        { item: 'Entrenadores', min: '1 paquete' },
        { item: 'Popotes', min: '1/2 paquete' },
        { item: 'Papel impresora', min: '1 paquete' },
        { item: 'Rollos Terminal', min: '1 paquete' },
        { item: 'Salsa Maggi', min: '1' },
        { item: 'Salsa Inglesa', min: '1' },
      ],
    },
  },
};

// Número opcional de WhatsApp del dueño para que el botón abra chat directo.
// Formato internacional sin "+": 52 seguido del número. Dejar vacío abre selector de contacto.
export const WHATSAPP_DESTINO = '';
